# Generated by Django 2.2.6 on 2020-03-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='oauth',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
